### ISSUE TITLE
warp is broken in 1.13

### ISSUE THREAD

**Issue by Sleepybear** [SupremeMortal/EssentialsNK#15]
First, when I tried /warp <playername> <warpname>, it said could not find warp <playername>, so then I just tried /warp <warpname> and got this error:

```java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.List
        at cn.yescallop.essentialsnk.EssentialsAPI.getWarp(EssentialsAPI.java:434) ~[?:?]
        at cn.yescallop.essentialsnk.command.defaults.warp.WarpCommand.execute(WarpCommand.java:47) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:751) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2730) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
        at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2075) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:80) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1124) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:880) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:565) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]```

**Comment by Sleepybear** [comment]
So if I delete all my warp points, created a new one, I got same error until I reloaded the server. Now it works for that warp point. If I create another warp point, I can use my first warp point, but the new one throws the error. If I reload the server, the new warp point works.

**Comment by jrodr10** [comment]
```16:57:22 [ERROR] Throwing
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class java.util.List ([Ljava.lang.Object; and java.util.List are in module java.base of loader 'bootstrap')
        at cn.yescallop.essentialsnk.EssentialsAPI.getWarp(EssentialsAPI.java:434) ~[?:?]
        at cn.yescallop.essentialsnk.command.defaults.warp.WarpCommand.execute(WarpCommand.java:47) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:760) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2803) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at cn.nukkit.network.Network.processPackets(Network.java:196) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:181) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2092) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:84) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1133) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:912) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:889) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:571) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
```
same issue 1.14

**Comment by SupremeMortal** [comment]
Please try the latest build
